n1 = int(input("Digite um valor"))
n2 = int(input("Digite outro valor"))
print(f"A soma de {n1} e {n2} em adição é: {n1+n2}")
print(f"A soma de {n1} e {n2} em subtração é: {n1-n2}")
print(f"A soma de {n1} e {n2} em multiplicação é: {n1*n2}")
print(f"a soma de {n1} e {n2} em exponenciação é: {n1**n2}")
print(f"A soma de {n1} e {n2} em divisão é: {n1/n2}")
print(f"O resto dessa divisão é: {n1%n2}")
print(f"O resultado inteiro dessa divisão é: {n1//n2}")